### ISSUE TITLE
Command Argument Registry

### ISSUE THREAD

**Issue by CyanideX** [CreativeMD/CMDCam#66]
Need to add command arguments to the `COMMAND_ARGUMENT_TYPE_REGISTRY`.

https://github.com/CreativeMD/CMDCam/blob/1.19/src/main/java/team/creative/cmdcam/CMDCam.java#L83-L87

Log: https://paste.ee/p/0tT5q

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue.

**Comment by CyanideX** [comment]
It seems you missed one argument:

https://github.com/CreativeMD/CMDCam/blob/1.19/src/main/java/team/creative/cmdcam/common/command/argument/CamPitchModeArgument.java

**Comment by CreativeMD** [comment]
Fixed! Thanks for reminding me.

**Comment by CyanideX** [comment]
Great! Will you be releasing the updated lib too? I'm currently having issues with it trying to find a method from CreativeCore.

**Comment by CreativeMD** [comment]
Answered you on discord. New CreativeCore version is out and the fov issue will be fixed soon.
